import {Injectable} from '@angular/core';
import {Observable, of} from 'rxjs';
import {map} from 'rxjs/operators';

import {Folder, Library, LibraryFile} from '@app/models/file';

@Injectable()
export class FilesService {

  movies: Library = { type: 'library', path: '/f', name: 'Movies', numberOfVideos: 7 };
  shows: Library = { type: 'library', path: '/f/s', name: 'TV Shows', numberOfVideos: 3 };
  korra: Library = {name: 'Vidéos', numberOfVideos: 0, path: 'D: \\Vidéos\\Avatar - The Legend of Korra', type: 'library'};

  testUrl = 'http://127.0.0.1:8887/Captain.Fantastic.2016.1080p.BluRay.6CH.ShAaNiG.mkv?static=1';

/*  files: File[] = [
    { path: '/f/movie2.mkv', name: 'movie2.mkv', parent: '/f', type: 'file', size: 1,
      url: 'http://127.0.0.1:8887/Assassins.Creed.2016.1080p.BluRay.x265.ShAaNiG.mkv?static=1' },
    { path: '/f/movie1.mkv', name: 'movie1.mkv', parent: '/f', type: 'file', size: 1,
      url: 'http://127.0.0.1:8887/Alice%20Au%20Pays%20Des%20Merveilles%20-%20Multi%20-%201080p%20mHDgz.mkv?static=1' },
    { path: '/f/subfolder', name: 'subfolder', parent: '/f', type: 'folder', numberOfVideos: 2 },
    { path: '/f/subfolder/sub-movie1.mkv', name: 'sub-movie1.mkv', parent: '/f/subfolder', type: 'file', size: 1, url: this.testUrl },
    { path: '/f/subfolder/sub-movie2.mkv', name: 'sub-movie2.mkv', parent: '/f/subfolder', type: 'file', size: 1, url: this.testUrl },
    { path: '/f/s/sub', name: 'sub', parent: '/f/s', type: 'folder', numberOfVideos: 1 },
    { path: '/f/s/sub/test.mkv', name: 'test.mkv', parent: '/f/s/sub', type: 'file', size: 1, url: this.testUrl },
    { path: '/f/s/show1.mkv', name: 'show1.mkv', parent: '/f/s', type: 'file', size: 1, url: this.testUrl },
    { path: '/f/s/show2.mkv', name: 'show2.mkv', parent: '/f/s', type: 'file', size: 1, url: this.testUrl },
    { path: '/f/s', name: 's', parent: '/f', type: 'folder', numberOfVideos: 3 },
  ];*/

  files: LibraryFile[] = [
    {name: 'Featurettes4', numberOfVideos: 0, parent: 'D: \\Vidéos\\Avatar - The Legend of Korra', path: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Featurettes4', type: 'folder'},
    {format: 'mkv', name: '2014 Comic-Con Panel.mkv', parent: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Featurettes4', path: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Featurettes4\\2014 Comic-Con Panel.mkv', size: 983303188480, type: 'file', url: 'http://localhost/2014+Comic-Con+Panel.mkv'},
    {format: 'mkv', name: 'Kuvira vs. Prince Wu.mkv', parent: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Featurettes4', path: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Featurettes4\\Kuvira vs. Prince Wu.mkv', size: 983303188480, type: 'file', url: 'http://localhost/Kuvira+vs.+Prince+Wu.mkv'},
    {format: 'mkv', name: 'Menu Art (1).mkv', parent: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Featurettes4', path: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Featurettes4\\Menu Art (1).mkv', size: 983303188480, type: 'file', url: 'http://localhost/Menu+Art+%281%29.mkv'},
    {format: 'mkv', name: 'Menu Art (2).mkv', parent: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Featurettes4', path: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Featurettes4\\Menu Art (2).mkv', size: 983303188480, type: 'file', url: 'http://localhost/Menu+Art+%282%29.mkv'},
    {format: 'mkv', name: 'Republic City Hustle - Part 1.mkv', parent: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Featurettes4', path: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Featurettes4\\Republic City Hustle - Part 1.mkv', size: 983303188480, type: 'file', url: 'http://localhost/Republic+City+Hustle+-+Part+1.mkv'},
    {format: 'mkv', name: 'Republic City Hustle - Part 2.mkv', parent: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Featurettes4', path: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Featurettes4\\Republic City Hustle - Part 2.mkv', size: 983303188480, type: 'file', url: 'http://localhost/Republic+City+Hustle+-+Part+2.mkv'},
    {format: 'mkv', name: 'Republic City Hustle - Part 3.mkv', parent: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Featurettes4', path: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Featurettes4\\Republic City Hustle - Part 3.mkv', size: 983303188480, type: 'file', url: 'http://localhost/Republic+City+Hustle+-+Part+3.mkv'},
    {format: 'mkv', name: 'The Making of a Legend - The Untold Story Part 2.mkv', parent: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Featurettes4', path: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Featurettes4\\The Making of a Legend - The Untold Story Part 2.mkv', size: 983303188480, type: 'file', url: 'http://localhost/The+Making+of+a+Legend+-+The+Untold+Story+Part+2.mkv'},
    {name: 'Season 1', numberOfVideos: 0, parent: 'D: \\Vidéos\\Avatar - The Legend of Korra', path: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 1', type: 'folder'},
    {name: 'Featurettes1', numberOfVideos: 0, parent: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 1', path: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 1\\Featurettes1', type: 'folder'},
    {format: 'mkv', name: 'Creator\'s Favorite Animatics Scene - And the Winner Is.mkv', parent: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 1\\Featurettes1', path: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 1\\Featurettes1\\Creator\'s Favorite Animatics Scene - And the Winner Is.mkv', size: 983303188480, type: 'file', url: 'http://localhost/Creator%27s+Favorite+Animatics+Scene+-+And+the+Winner+Is.mkv'},
    {format: 'mkv', name: 'Creator\'s Favorite Animatics Scene - Endgame.mkv', parent: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 1\\Featurettes1', path: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 1\\Featurettes1\\Creator\'s Favorite Animatics Scene - Endgame.mkv', size: 983303188480, type: 'file', url: 'http://localhost/Creator%27s+Favorite+Animatics+Scene+-+Endgame.mkv'},
    {format: 'mkv', name: 'Creator\'s Favorite Animatics Scene - The Revelation.mkv', parent: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 1\\Featurettes1', path: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 1\\Featurettes1\\Creator\'s Favorite Animatics Scene - The Revelation.mkv', size: 983303188480, type: 'file', url: 'http://localhost/Creator%27s+Favorite+Animatics+Scene+-+The+Revelation.mkv'},
    {format: 'mkv', name: 'Creator\'s Favorite Animatics Scene - The Spirit of Competition.mkv', parent: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 1\\Featurettes1', path: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 1\\Featurettes1\\Creator\'s Favorite Animatics Scene - The Spirit of Competition.mkv', size: 983303188480, type: 'file', url: 'http://localhost/Creator%27s+Favorite+Animatics+Scene+-+The+Spirit+of+Competition.mkv'},
    {format: 'mkv', name: 'Creator\'s Favorite Animatics Scene - The Voice in the Night.mkv', parent: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 1\\Featurettes1', path: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 1\\Featurettes1\\Creator\'s Favorite Animatics Scene - The Voice in the Night.mkv', size: 983303188480, type: 'file', url: 'http://localhost/Creator%27s+Favorite+Animatics+Scene+-+The+Voice+in+the+Night.mkv'},
    {format: 'mkv', name: 'Creator\'s Favorite Animatics Scene - Turning the Tides.mkv', parent: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 1\\Featurettes1', path: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 1\\Featurettes1\\Creator\'s Favorite Animatics Scene - Turning the Tides.mkv', size: 983303188480, type: 'file', url: 'http://localhost/Creator%27s+Favorite+Animatics+Scene+-+Turning+the+Tides.mkv'},
    {format: 'mkv', name: 'Creator\'s Favorite Animatics Scene - Welcome to Republic City.mkv', parent: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 1\\Featurettes1', path: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 1\\Featurettes1\\Creator\'s Favorite Animatics Scene - Welcome to Republic City.mkv', size: 983303188480, type: 'file', url: 'http://localhost/Creator%27s+Favorite+Animatics+Scene+-+Welcome+to+Republic+City.mkv'},
    {format: 'mkv', name: 'Creator\'s Favorite Animatics Scene - When Extremes Meet.mkv', parent: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 1\\Featurettes1', path: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 1\\Featurettes1\\Creator\'s Favorite Animatics Scene - When Extremes Meet.mkv', size: 983303188480, type: 'file', url: 'http://localhost/Creator%27s+Favorite+Animatics+Scene+-+When+Extremes+Meet.mkv'},
    {format: 'mkv', name: 'Menu Art.mkv', parent: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 1\\Featurettes1', path: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 1\\Featurettes1\\Menu Art.mkv', size: 983303188480, type: 'file', url: 'http://localhost/Menu+Art.mkv'},
    {format: 'mkv', name: 'The Making of a Legend - The Untold Story.mkv', parent: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 1\\Featurettes1', path: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 1\\Featurettes1\\The Making of a Legend - The Untold Story.mkv', size: 983303188480, type: 'file', url: 'http://localhost/The+Making+of+a+Legend+-+The+Untold+Story.mkv'},
    {format: 'mkv', name: 'The Legend of Korra (2012) - S01E01 - Welcome to Republic City (1080p BluRay x265 RCVR).mkv', parent: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 1', path: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 1\\The Legend of Korra (2012) - S01E01 - Welcome to Republic City (1080p BluRay x265 RCVR).mkv', size: 983303188480, type: 'file', url: 'http://localhost/The+Legend+of+Korra+%282012%29+-+S01E01+-+Welcome+to+Republic+City+%281080p+BluRay+x265+RCVR%29.mkv'},
    {format: 'mkv', name: 'The Legend of Korra (2012) - S01E02 - A Leaf in the Wind (1080p BluRay x265 RCVR).mkv', parent: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 1', path: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 1\\The Legend of Korra (2012) - S01E02 - A Leaf in the Wind (1080p BluRay x265 RCVR).mkv', size: 983303188480, type: 'file', url: 'http://localhost/The+Legend+of+Korra+%282012%29+-+S01E02+-+A+Leaf+in+the+Wind+%281080p+BluRay+x265+RCVR%29.mkv'},
    {format: 'mkv', name: 'The Legend of Korra (2012) - S01E03 - The Revelation (1080p BluRay x265 RCVR).mkv', parent: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 1', path: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 1\\The Legend of Korra (2012) - S01E03 - The Revelation (1080p BluRay x265 RCVR).mkv', size: 983303188480, type: 'file', url: 'http://localhost/The+Legend+of+Korra+%282012%29+-+S01E03+-+The+Revelation+%281080p+BluRay+x265+RCVR%29.mkv'},
    {format: 'mkv', name: 'The Legend of Korra (2012) - S01E04 - The Voice in the Night (1080p BluRay x265 RCVR).mkv', parent: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 1', path: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 1\\The Legend of Korra (2012) - S01E04 - The Voice in the Night (1080p BluRay x265 RCVR).mkv', size: 983303188480, type: 'file', url: 'http://localhost/The+Legend+of+Korra+%282012%29+-+S01E04+-+The+Voice+in+the+Night+%281080p+BluRay+x265+RCVR%29.mkv'},
    {format: 'mkv', name: 'The Legend of Korra (2012) - S01E05 - The Spirit of Competition (1080p BluRay x265 RCVR).mkv', parent: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 1', path: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 1\\The Legend of Korra (2012) - S01E05 - The Spirit of Competition (1080p BluRay x265 RCVR).mkv', size: 983303188480, type: 'file', url: 'http://localhost/The+Legend+of+Korra+%282012%29+-+S01E05+-+The+Spirit+of+Competition+%281080p+BluRay+x265+RCVR%29.mkv'},
    {format: 'mkv', name: 'The Legend of Korra (2012) - S01E06 - And the Winner Is... (1080p BluRay x265 RCVR).mkv', parent: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 1', path: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 1\\The Legend of Korra (2012) - S01E06 - And the Winner Is... (1080p BluRay x265 RCVR).mkv', size: 983303188480, type: 'file', url: 'http://localhost/The+Legend+of+Korra+%282012%29+-+S01E06+-+And+the+Winner+Is...+%281080p+BluRay+x265+RCVR%29.mkv'},
    {format: 'mkv', name: 'The Legend of Korra (2012) - S01E07 - The Aftermath (1080p BluRay x265 RCVR).mkv', parent: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 1', path: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 1\\The Legend of Korra (2012) - S01E07 - The Aftermath (1080p BluRay x265 RCVR).mkv', size: 983303188480, type: 'file', url: 'http://localhost/The+Legend+of+Korra+%282012%29+-+S01E07+-+The+Aftermath+%281080p+BluRay+x265+RCVR%29.mkv'},
    {format: 'mkv', name: 'The Legend of Korra (2012) - S01E08 - When Extremes Meet (1080p BluRay x265 RCVR).mkv', parent: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 1', path: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 1\\The Legend of Korra (2012) - S01E08 - When Extremes Meet (1080p BluRay x265 RCVR).mkv', size: 983303188480, type: 'file', url: 'http://localhost/The+Legend+of+Korra+%282012%29+-+S01E08+-+When+Extremes+Meet+%281080p+BluRay+x265+RCVR%29.mkv'},
    {format: 'mkv', name: 'The Legend of Korra (2012) - S01E09 - Out of the Past (1080p BluRay x265 RCVR).mkv', parent: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 1', path: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 1\\The Legend of Korra (2012) - S01E09 - Out of the Past (1080p BluRay x265 RCVR).mkv', size: 983303188480, type: 'file', url: 'http://localhost/The+Legend+of+Korra+%282012%29+-+S01E09+-+Out+of+the+Past+%281080p+BluRay+x265+RCVR%29.mkv'},
    {format: 'mkv', name: 'The Legend of Korra (2012) - S01E10 - Turning the Tides (1080p BluRay x265 RCVR).mkv', parent: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 1', path: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 1\\The Legend of Korra (2012) - S01E10 - Turning the Tides (1080p BluRay x265 RCVR).mkv', size: 983303188480, type: 'file', url: 'http://localhost/The+Legend+of+Korra+%282012%29+-+S01E10+-+Turning+the+Tides+%281080p+BluRay+x265+RCVR%29.mkv'},
    {format: 'mkv', name: 'The Legend of Korra (2012) - S01E11 - Skeletons in the Closet (1080p BluRay x265 RCVR).mkv', parent: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 1', path: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 1\\The Legend of Korra (2012) - S01E11 - Skeletons in the Closet (1080p BluRay x265 RCVR).mkv', size: 983303188480, type: 'file', url: 'http://localhost/The+Legend+of+Korra+%282012%29+-+S01E11+-+Skeletons+in+the+Closet+%281080p+BluRay+x265+RCVR%29.mkv'},
    {format: 'mkv', name: 'The Legend of Korra (2012) - S01E12 - Endgame (1080p BluRay x265 RCVR).mkv', parent: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 1', path: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 1\\The Legend of Korra (2012) - S01E12 - Endgame (1080p BluRay x265 RCVR).mkv', size: 983303188480, type: 'file', url: 'http://localhost/The+Legend+of+Korra+%282012%29+-+S01E12+-+Endgame+%281080p+BluRay+x265+RCVR%29.mkv'},
    {name: 'Season 2', numberOfVideos: 0, parent: 'D: \\Vidéos\\Avatar - The Legend of Korra', path: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 2', type: 'folder'},
    {name: 'Featurettes2', numberOfVideos: 0, parent: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 2', path: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 2\\Featurettes2', type: 'folder'},
    {format: 'mkv', name: 'Feuding Spirts Korra’s Family.mkv', parent: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 2\\Featurettes2', path: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 2\\Featurettes2\\Feuding Spirts Korra’s Family.mkv', size: 983303188480, type: 'file', url: 'http://localhost/Feuding+Spirts+Korra%E2%80%99s+Family.mkv'},
    {format: 'mkv', name: 'Inside the Book of Spirts.mkv', parent: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 2\\Featurettes2', path: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 2\\Featurettes2\\Inside the Book of Spirts.mkv', size: 983303188480, type: 'file', url: 'http://localhost/Inside+the+Book+of+Spirts.mkv'},
    {format: 'mkv', name: 'Kindred Spirts Tenzin’s Family.mkv', parent: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 2\\Featurettes2', path: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 2\\Featurettes2\\Kindred Spirts Tenzin’s Family.mkv', size: 983303188480, type: 'file', url: 'http://localhost/Kindred+Spirts+Tenzin%E2%80%99s+Family.mkv'},
    {format: 'mkv', name: 'Menu Art Disk 1.mkv', parent: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 2\\Featurettes2', path: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 2\\Featurettes2\\Menu Art Disk 1.mkv', size: 983303188480, type: 'file', url: 'http://localhost/Menu+Art+Disk+1.mkv'},
    {format: 'mkv', name: 'Menu Art Disk 2.mkv', parent: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 2\\Featurettes2', path: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 2\\Featurettes2\\Menu Art Disk 2.mkv', size: 983303188480, type: 'file', url: 'http://localhost/Menu+Art+Disk+2.mkv'},
    {name: 'Scene Bending', numberOfVideos: 0, parent: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 2\\Featurettes2', path: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 2\\Featurettes2\\Scene Bending', type: 'folder'},
    {format: 'mkv', name: 'A New Spiritual Age.mkv', parent: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 2\\Featurettes2\\Scene Bending', path: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 2\\Featurettes2\\Scene Bending\\A New Spiritual Age.mkv', size: 983303188480, type: 'file', url: 'http://localhost/A+New+Spiritual+Age.mkv'},
    {format: 'mkv', name: 'Beginnings,  Part 1.mkv', parent: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 2\\Featurettes2\\Scene Bending', path: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 2\\Featurettes2\\Scene Bending\\Beginnings,  Part 1.mkv', size: 983303188480, type: 'file', url: 'http://localhost/Beginnings%2C+Part+1.mkv'},
    {format: 'mkv', name: 'Beginnings,  Part 2.mkv', parent: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 2\\Featurettes2\\Scene Bending', path: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 2\\Featurettes2\\Scene Bending\\Beginnings,  Part 2.mkv', size: 983303188480, type: 'file', url: 'http://localhost/Beginnings%2C+Part+2.mkv'},
    {format: 'mkv', name: 'Civil Wars,  Part 1.mkv', parent: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 2\\Featurettes2\\Scene Bending', path: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 2\\Featurettes2\\Scene Bending\\Civil Wars,  Part 1.mkv', size: 983303188480, type: 'file', url: 'http://localhost/Civil+Wars%2C+Part+1.mkv'},
    {format: 'mkv', name: 'Civil Wars,  Part 2.mkv', parent: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 2\\Featurettes2\\Scene Bending', path: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 2\\Featurettes2\\Scene Bending\\Civil Wars,  Part 2.mkv', size: 983303188480, type: 'file', url: 'http://localhost/Civil+Wars%2C+Part+2.mkv'},
    {format: 'mkv', name: 'Darkness Falls.mkv', parent: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 2\\Featurettes2\\Scene Bending', path: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 2\\Featurettes2\\Scene Bending\\Darkness Falls.mkv', size: 983303188480, type: 'file', url: 'http://localhost/Darkness+Falls.mkv'},
    {format: 'mkv', name: 'Harmonic Convergence.mkv', parent: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 2\\Featurettes2\\Scene Bending', path: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 2\\Featurettes2\\Scene Bending\\Harmonic Convergence.mkv', size: 983303188480, type: 'file', url: 'http://localhost/Harmonic+Convergence.mkv'},
    {format: 'mkv', name: 'Light in the Dark.mkv', parent: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 2\\Featurettes2\\Scene Bending', path: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 2\\Featurettes2\\Scene Bending\\Light in the Dark.mkv', size: 983303188480, type: 'file', url: 'http://localhost/Light+in+the+Dark.mkv'},
    {format: 'mkv', name: 'Night of a Thousand Stars.mkv', parent: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 2\\Featurettes2\\Scene Bending', path: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 2\\Featurettes2\\Scene Bending\\Night of a Thousand Stars.mkv', size: 983303188480, type: 'file', url: 'http://localhost/Night+of+a+Thousand+Stars.mkv'},
    {format: 'mkv', name: 'Peacekeepers Scene 1.mkv', parent: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 2\\Featurettes2\\Scene Bending', path: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 2\\Featurettes2\\Scene Bending\\Peacekeepers Scene 1.mkv', size: 983303188480, type: 'file', url: 'http://localhost/Peacekeepers+Scene+1.mkv'},
    {format: 'mkv', name: 'Rebel Spirt Scene 1.mkv', parent: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 2\\Featurettes2\\Scene Bending', path: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 2\\Featurettes2\\Scene Bending\\Rebel Spirt Scene 1.mkv', size: 983303188480, type: 'file', url: 'http://localhost/Rebel+Spirt+Scene+1.mkv'},
    {format: 'mkv', name: 'Rebel Spirt Scene 2.mkv', parent: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 2\\Featurettes2\\Scene Bending', path: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 2\\Featurettes2\\Scene Bending\\Rebel Spirt Scene 2.mkv', size: 983303188480, type: 'file', url: 'http://localhost/Rebel+Spirt+Scene+2.mkv'},
    {format: 'mkv', name: 'The Guide.mkv', parent: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 2\\Featurettes2\\Scene Bending', path: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 2\\Featurettes2\\Scene Bending\\The Guide.mkv', size: 983303188480, type: 'file', url: 'http://localhost/The+Guide.mkv'},
    {format: 'mkv', name: 'The Southern Lights Scene 1.mkv', parent: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 2\\Featurettes2\\Scene Bending', path: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 2\\Featurettes2\\Scene Bending\\The Southern Lights Scene 1.mkv', size: 983303188480, type: 'file', url: 'http://localhost/The+Southern+Lights+Scene+1.mkv'},
    {format: 'mkv', name: 'The Southern Lights Scene 2.mkv', parent: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 2\\Featurettes2\\Scene Bending', path: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 2\\Featurettes2\\Scene Bending\\The Southern Lights Scene 2.mkv', size: 983303188480, type: 'file', url: 'http://localhost/The+Southern+Lights+Scene+2.mkv'},
    {format: 'mkv', name: 'The Re-telling of Korra’s Journey.mkv', parent: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 2\\Featurettes2', path: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 2\\Featurettes2\\The Re-telling of Korra’s Journey.mkv', size: 983303188480, type: 'file', url: 'http://localhost/The+Re-telling+of+Korra%E2%80%99s+Journey.mkv'},
    {format: 'mkv', name: 'The Legend of Korra (2012) - S02E01 - Rebel Spirit (1080p BluRay x265 RCVR).mkv', parent: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 2', path: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 2\\The Legend of Korra (2012) - S02E01 - Rebel Spirit (1080p BluRay x265 RCVR).mkv', size: 983303188480, type: 'file', url: 'http://localhost/The+Legend+of+Korra+%282012%29+-+S02E01+-+Rebel+Spirit+%281080p+BluRay+x265+RCVR%29.mkv'},
    {format: 'mkv', name: 'The Legend of Korra (2012) - S02E02 - The Southern Lights (1080p BluRay x265 RCVR).mkv', parent: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 2', path: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 2\\The Legend of Korra (2012) - S02E02 - The Southern Lights (1080p BluRay x265 RCVR).mkv', size: 983303188480, type: 'file', url: 'http://localhost/The+Legend+of+Korra+%282012%29+-+S02E02+-+The+Southern+Lights+%281080p+BluRay+x265+RCVR%29.mkv'},
    {format: 'mkv', name: 'The Legend of Korra (2012) - S02E03 - Civil Wars (1) (1080p BluRay x265 RCVR).mkv', parent: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 2', path: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 2\\The Legend of Korra (2012) - S02E03 - Civil Wars (1) (1080p BluRay x265 RCVR).mkv', size: 983303188480, type: 'file', url: 'http://localhost/The+Legend+of+Korra+%282012%29+-+S02E03+-+Civil+Wars+%281%29+%281080p+BluRay+x265+RCVR%29.mkv'},
    {format: 'mkv', name: 'The Legend of Korra (2012) - S02E04 - Civil Wars (2) (1080p BluRay x265 RCVR).mkv', parent: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 2', path: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 2\\The Legend of Korra (2012) - S02E04 - Civil Wars (2) (1080p BluRay x265 RCVR).mkv', size: 983303188480, type: 'file', url: 'http://localhost/The+Legend+of+Korra+%282012%29+-+S02E04+-+Civil+Wars+%282%29+%281080p+BluRay+x265+RCVR%29.mkv'},
    {format: 'mkv', name: 'The Legend of Korra (2012) - S02E05 - Peacekeepers (1080p BluRay x265 RCVR).mkv', parent: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 2', path: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 2\\The Legend of Korra (2012) - S02E05 - Peacekeepers (1080p BluRay x265 RCVR).mkv', size: 983303188480, type: 'file', url: 'http://localhost/The+Legend+of+Korra+%282012%29+-+S02E05+-+Peacekeepers+%281080p+BluRay+x265+RCVR%29.mkv'},
    {format: 'mkv', name: 'The Legend of Korra (2012) - S02E06 - The Sting (1080p BluRay x265 RCVR).mkv', parent: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 2', path: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 2\\The Legend of Korra (2012) - S02E06 - The Sting (1080p BluRay x265 RCVR).mkv', size: 983303188480, type: 'file', url: 'http://localhost/The+Legend+of+Korra+%282012%29+-+S02E06+-+The+Sting+%281080p+BluRay+x265+RCVR%29.mkv'},
    {format: 'mkv', name: 'The Legend of Korra (2012) - S02E07 - The Beginnings Part 1 (1080p BluRay x265 RCVR).mkv', parent: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 2', path: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 2\\The Legend of Korra (2012) - S02E07 - The Beginnings Part 1 (1080p BluRay x265 RCVR).mkv', size: 983303188480, type: 'file', url: 'http://localhost/The+Legend+of+Korra+%282012%29+-+S02E07+-+The+Beginnings+Part+1+%281080p+BluRay+x265+RCVR%29.mkv'},
    {format: 'mkv', name: 'The Legend of Korra (2012) - S02E08 - The Beginnings Part 2 (1080p BluRay x265 RCVR).mkv', parent: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 2', path: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 2\\The Legend of Korra (2012) - S02E08 - The Beginnings Part 2 (1080p BluRay x265 RCVR).mkv', size: 983303188480, type: 'file', url: 'http://localhost/The+Legend+of+Korra+%282012%29+-+S02E08+-+The+Beginnings+Part+2+%281080p+BluRay+x265+RCVR%29.mkv'},
    {format: 'mkv', name: 'The Legend of Korra (2012) - S02E09 - The Guide (1080p BluRay x265 RCVR).mkv', parent: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 2', path: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 2\\The Legend of Korra (2012) - S02E09 - The Guide (1080p BluRay x265 RCVR).mkv', size: 983303188480, type: 'file', url: 'http://localhost/The+Legend+of+Korra+%282012%29+-+S02E09+-+The+Guide+%281080p+BluRay+x265+RCVR%29.mkv'},
    {format: 'mkv', name: 'The Legend of Korra (2012) - S02E10 - A New Spiritual Age (1080p BluRay x265 RCVR).mkv', parent: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 2', path: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 2\\The Legend of Korra (2012) - S02E10 - A New Spiritual Age (1080p BluRay x265 RCVR).mkv', size: 983303188480, type: 'file', url: 'http://localhost/The+Legend+of+Korra+%282012%29+-+S02E10+-+A+New+Spiritual+Age+%281080p+BluRay+x265+RCVR%29.mkv'},
    {format: 'mkv', name: 'The Legend of Korra (2012) - S02E11 - Night of a Thousand Stars (1080p BluRay x265 RCVR).mkv', parent: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 2', path: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 2\\The Legend of Korra (2012) - S02E11 - Night of a Thousand Stars (1080p BluRay x265 RCVR).mkv', size: 983303188480, type: 'file', url: 'http://localhost/The+Legend+of+Korra+%282012%29+-+S02E11+-+Night+of+a+Thousand+Stars+%281080p+BluRay+x265+RCVR%29.mkv'},
    {format: 'mkv', name: 'The Legend of Korra (2012) - S02E12 - Harmonic Convergence (1080p BluRay x265 RCVR).mkv', parent: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 2', path: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 2\\The Legend of Korra (2012) - S02E12 - Harmonic Convergence (1080p BluRay x265 RCVR).mkv', size: 983303188480, type: 'file', url: 'http://localhost/The+Legend+of+Korra+%282012%29+-+S02E12+-+Harmonic+Convergence+%281080p+BluRay+x265+RCVR%29.mkv'},
    {format: 'mkv', name: 'The Legend of Korra (2012) - S02E13 - Darkness Falls (1080p BluRay x265 RCVR).mkv', parent: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 2', path: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 2\\The Legend of Korra (2012) - S02E13 - Darkness Falls (1080p BluRay x265 RCVR).mkv', size: 983303188480, type: 'file', url: 'http://localhost/The+Legend+of+Korra+%282012%29+-+S02E13+-+Darkness+Falls+%281080p+BluRay+x265+RCVR%29.mkv'},
    {format: 'mkv', name: 'The Legend of Korra (2012) - S02E14 - Light in the Dark (1080p BluRay x265 RCVR).mkv', parent: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 2', path: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 2\\The Legend of Korra (2012) - S02E14 - Light in the Dark (1080p BluRay x265 RCVR).mkv', size: 983303188480, type: 'file', url: 'http://localhost/The+Legend+of+Korra+%282012%29+-+S02E14+-+Light+in+the+Dark+%281080p+BluRay+x265+RCVR%29.mkv'},
    {name: 'Season 3', numberOfVideos: 0, parent: 'D: \\Vidéos\\Avatar - The Legend of Korra', path: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 3', type: 'folder'},
    {name: 'Featurettes3', numberOfVideos: 0, parent: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 3', path: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 3\\Featurettes3', type: 'folder'},
    {format: 'mkv', name: 'Menu Art Disk 1.mkv', parent: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 3\\Featurettes3', path: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 3\\Featurettes3\\Menu Art Disk 1.mkv', size: 983303188480, type: 'file', url: 'http://localhost/Menu+Art+Disk+1.mkv'},
    {format: 'mkv', name: 'Menu Art Disk 2.mkv', parent: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 3\\Featurettes3', path: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 3\\Featurettes3\\Menu Art Disk 2.mkv', size: 983303188480, type: 'file', url: 'http://localhost/Menu+Art+Disk+2.mkv'},
    {name: 'The Spirit of an Episode', numberOfVideos: 0, parent: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 3\\Featurettes3', path: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 3\\Featurettes3\\The Spirit of an Episode', type: 'folder'},
    {format: 'mkv', name: 'A Breath of Fresh Air.mkv', parent: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 3\\Featurettes3\\The Spirit of an Episode', path: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 3\\Featurettes3\\The Spirit of an Episode\\A Breath of Fresh Air.mkv', size: 983303188480, type: 'file', url: 'http://localhost/A+Breath+of+Fresh+Air.mkv'},
    {format: 'mkv', name: 'Enter The Void.mkv', parent: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 3\\Featurettes3\\The Spirit of an Episode', path: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 3\\Featurettes3\\The Spirit of an Episode\\Enter The Void.mkv', size: 983303188480, type: 'file', url: 'http://localhost/Enter+The+Void.mkv'},
    {format: 'mkv', name: 'In Harm’s Way.mkv', parent: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 3\\Featurettes3\\The Spirit of an Episode', path: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 3\\Featurettes3\\The Spirit of an Episode\\In Harm’s Way.mkv', size: 983303188480, type: 'file', url: 'http://localhost/In+Harm%E2%80%99s+Way.mkv'},
    {format: 'mkv', name: 'Long Live The Queen.mkv', parent: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 3\\Featurettes3\\The Spirit of an Episode', path: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 3\\Featurettes3\\The Spirit of an Episode\\Long Live The Queen.mkv', size: 983303188480, type: 'file', url: 'http://localhost/Long+Live+The+Queen.mkv'},
    {format: 'mkv', name: 'Old Wounds.mkv', parent: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 3\\Featurettes3\\The Spirit of an Episode', path: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 3\\Featurettes3\\The Spirit of an Episode\\Old Wounds.mkv', size: 983303188480, type: 'file', url: 'http://localhost/Old+Wounds.mkv'},
    {format: 'mkv', name: 'Original Airbenders.mkv', parent: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 3\\Featurettes3\\The Spirit of an Episode', path: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 3\\Featurettes3\\The Spirit of an Episode\\Original Airbenders.mkv', size: 983303188480, type: 'file', url: 'http://localhost/Original+Airbenders.mkv'},
    {format: 'mkv', name: 'Rebirth.mkv', parent: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 3\\Featurettes3\\The Spirit of an Episode', path: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 3\\Featurettes3\\The Spirit of an Episode\\Rebirth.mkv', size: 983303188480, type: 'file', url: 'http://localhost/Rebirth.mkv'},
    {format: 'mkv', name: 'The Earth Queen.mkv', parent: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 3\\Featurettes3\\The Spirit of an Episode', path: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 3\\Featurettes3\\The Spirit of an Episode\\The Earth Queen.mkv', size: 983303188480, type: 'file', url: 'http://localhost/The+Earth+Queen.mkv'},
    {format: 'mkv', name: 'The Metal Clan.mkv', parent: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 3\\Featurettes3\\The Spirit of an Episode', path: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 3\\Featurettes3\\The Spirit of an Episode\\The Metal Clan.mkv', size: 983303188480, type: 'file', url: 'http://localhost/The+Metal+Clan.mkv'},
    {format: 'mkv', name: 'The Stakeout.mkv', parent: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 3\\Featurettes3\\The Spirit of an Episode', path: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 3\\Featurettes3\\The Spirit of an Episode\\The Stakeout.mkv', size: 983303188480, type: 'file', url: 'http://localhost/The+Stakeout.mkv'},
    {format: 'mkv', name: 'The Terror Within.mkv', parent: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 3\\Featurettes3\\The Spirit of an Episode', path: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 3\\Featurettes3\\The Spirit of an Episode\\The Terror Within.mkv', size: 983303188480, type: 'file', url: 'http://localhost/The+Terror+Within.mkv'},
    {format: 'mkv', name: 'The Ultimatum.mkv', parent: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 3\\Featurettes3\\The Spirit of an Episode', path: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 3\\Featurettes3\\The Spirit of an Episode\\The Ultimatum.mkv', size: 983303188480, type: 'file', url: 'http://localhost/The+Ultimatum.mkv'},
    {format: 'mkv', name: 'Venom of the Red Lotus.mkv', parent: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 3\\Featurettes3\\The Spirit of an Episode', path: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 3\\Featurettes3\\The Spirit of an Episode\\Venom of the Red Lotus.mkv', size: 983303188480, type: 'file', url: 'http://localhost/Venom+of+the+Red+Lotus.mkv'},
    {format: 'mkv', name: 'The Legend of Korra (2012) - S03E01 - A Breath of Fresh Air (1080p BluRay x265 RCVR).mkv', parent: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 3', path: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 3\\The Legend of Korra (2012) - S03E01 - A Breath of Fresh Air (1080p BluRay x265 RCVR).mkv', size: 983303188480, type: 'file', url: 'http://localhost/The+Legend+of+Korra+%282012%29+-+S03E01+-+A+Breath+of+Fresh+Air+%281080p+BluRay+x265+RCVR%29.mkv'},
    {format: 'mkv', name: 'The Legend of Korra (2012) - S03E02 - Rebirth (1080p BluRay x265 RCVR).mkv', parent: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 3', path: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 3\\The Legend of Korra (2012) - S03E02 - Rebirth (1080p BluRay x265 RCVR).mkv', size: 983303188480, type: 'file', url: 'http://localhost/The+Legend+of+Korra+%282012%29+-+S03E02+-+Rebirth+%281080p+BluRay+x265+RCVR%29.mkv'},
    {format: 'mkv', name: 'The Legend of Korra (2012) - S03E03 - The Earth Queen (1080p BluRay x265 RCVR).mkv', parent: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 3', path: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 3\\The Legend of Korra (2012) - S03E03 - The Earth Queen (1080p BluRay x265 RCVR).mkv', size: 983303188480, type: 'file', url: 'http://localhost/The+Legend+of+Korra+%282012%29+-+S03E03+-+The+Earth+Queen+%281080p+BluRay+x265+RCVR%29.mkv'},
    {format: 'mkv', name: 'The Legend of Korra (2012) - S03E04 - In Harm\'s Way (1080p BluRay x265 RCVR).mkv', parent: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 3', path: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 3\\The Legend of Korra (2012) - S03E04 - In Harm\'s Way (1080p BluRay x265 RCVR).mkv', size: 983303188480, type: 'file', url: 'http://localhost/The+Legend+of+Korra+%282012%29+-+S03E04+-+In+Harm%27s+Way+%281080p+BluRay+x265+RCVR%29.mkv'},
    {format: 'mkv', name: 'The Legend of Korra (2012) - S03E05 - The Metal Clan (1080p BluRay x265 RCVR).mkv', parent: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 3', path: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 3\\The Legend of Korra (2012) - S03E05 - The Metal Clan (1080p BluRay x265 RCVR).mkv', size: 983303188480, type: 'file', url: 'http://localhost/The+Legend+of+Korra+%282012%29+-+S03E05+-+The+Metal+Clan+%281080p+BluRay+x265+RCVR%29.mkv'},
    {format: 'mkv', name: 'The Legend of Korra (2012) - S03E06 - Old Wounds (1080p BluRay x265 RCVR).mkv', parent: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 3', path: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 3\\The Legend of Korra (2012) - S03E06 - Old Wounds (1080p BluRay x265 RCVR).mkv', size: 983303188480, type: 'file', url: 'http://localhost/The+Legend+of+Korra+%282012%29+-+S03E06+-+Old+Wounds+%281080p+BluRay+x265+RCVR%29.mkv'},
    {format: 'mkv', name: 'The Legend of Korra (2012) - S03E07 - Original Airbenders (1080p BluRay x265 RCVR).mkv', parent: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 3', path: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 3\\The Legend of Korra (2012) - S03E07 - Original Airbenders (1080p BluRay x265 RCVR).mkv', size: 983303188480, type: 'file', url: 'http://localhost/The+Legend+of+Korra+%282012%29+-+S03E07+-+Original+Airbenders+%281080p+BluRay+x265+RCVR%29.mkv'},
    {format: 'mkv', name: 'The Legend of Korra (2012) - S03E08 - The Terror Within (1080p BluRay x265 RCVR).mkv', parent: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 3', path: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 3\\The Legend of Korra (2012) - S03E08 - The Terror Within (1080p BluRay x265 RCVR).mkv', size: 983303188480, type: 'file', url: 'http://localhost/The+Legend+of+Korra+%282012%29+-+S03E08+-+The+Terror+Within+%281080p+BluRay+x265+RCVR%29.mkv'},
    {format: 'mkv', name: 'The Legend of Korra (2012) - S03E09 - The Stakeout (1080p BluRay x265 RCVR).mkv', parent: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 3', path: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 3\\The Legend of Korra (2012) - S03E09 - The Stakeout (1080p BluRay x265 RCVR).mkv', size: 983303188480, type: 'file', url: 'http://localhost/The+Legend+of+Korra+%282012%29+-+S03E09+-+The+Stakeout+%281080p+BluRay+x265+RCVR%29.mkv'},
    {format: 'mkv', name: 'The Legend of Korra (2012) - S03E10 - Long Live the Queen (1080p BluRay x265 RCVR).mkv', parent: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 3', path: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 3\\The Legend of Korra (2012) - S03E10 - Long Live the Queen (1080p BluRay x265 RCVR).mkv', size: 983303188480, type: 'file', url: 'http://localhost/The+Legend+of+Korra+%282012%29+-+S03E10+-+Long+Live+the+Queen+%281080p+BluRay+x265+RCVR%29.mkv'},
    {format: 'mkv', name: 'The Legend of Korra (2012) - S03E11 - The Ultimatum (1080p BluRay x265 RCVR).mkv', parent: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 3', path: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 3\\The Legend of Korra (2012) - S03E11 - The Ultimatum (1080p BluRay x265 RCVR).mkv', size: 983303188480, type: 'file', url: 'http://localhost/The+Legend+of+Korra+%282012%29+-+S03E11+-+The+Ultimatum+%281080p+BluRay+x265+RCVR%29.mkv'},
    {format: 'mkv', name: 'The Legend of Korra (2012) - S03E12 - Enter the Void (1080p BluRay x265 RCVR).mkv', parent: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 3', path: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 3\\The Legend of Korra (2012) - S03E12 - Enter the Void (1080p BluRay x265 RCVR).mkv', size: 983303188480, type: 'file', url: 'http://localhost/The+Legend+of+Korra+%282012%29+-+S03E12+-+Enter+the+Void+%281080p+BluRay+x265+RCVR%29.mkv'},
    {format: 'mkv', name: 'The Legend of Korra (2012) - S03E13 - Venom of the Red Lotus (1080p BluRay x265 RCVR).mkv', parent: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 3', path: 'D: \\Vidéos\\Avatar - The Legend of Korra\\Season 3\\The Legend of Korra (2012) - S03E13 - Venom of the Red Lotus (1080p BluRay x265 RCVR).mkv', size: 983303188480, type: 'file', url: 'http://localhost/The+Legend+of+Korra+%282012%29+-+S03E13+-+Venom+of+the+Red+Lotus+%281080p+BluRay+x265+RCVR%29.mkv'},
    {format: 'mkv', name: 'The Legend of Korra (2012) - S04E01 - After All These Years (1080p BluRay x265 RCVR).mkv', parent: 'D: \\Vidéos\\Avatar - The Legend of Korra', path: 'D: \\Vidéos\\Avatar - The Legend of Korra\\The Legend of Korra (2012) - S04E01 - After All These Years (1080p BluRay x265 RCVR).mkv', size: 983303188480, type: 'file', url: 'http://localhost/The+Legend+of+Korra+%282012%29+-+S04E01+-+After+All+These+Years+%281080p+BluRay+x265+RCVR%29.mkv'},
    {format: 'mkv', name: 'The Legend of Korra (2012) - S04E02 - Korra Alone (1080p BluRay x265 RCVR).mkv', parent: 'D: \\Vidéos\\Avatar - The Legend of Korra', path: 'D: \\Vidéos\\Avatar - The Legend of Korra\\The Legend of Korra (2012) - S04E02 - Korra Alone (1080p BluRay x265 RCVR).mkv', size: 983303188480, type: 'file', url: 'http://localhost/The+Legend+of+Korra+%282012%29+-+S04E02+-+Korra+Alone+%281080p+BluRay+x265+RCVR%29.mkv'},
    {format: 'mkv', name: 'The Legend of Korra (2012) - S04E03 - The Coronation (1080p BluRay x265 RCVR).mkv', parent: 'D: \\Vidéos\\Avatar - The Legend of Korra', path: 'D: \\Vidéos\\Avatar - The Legend of Korra\\The Legend of Korra (2012) - S04E03 - The Coronation (1080p BluRay x265 RCVR).mkv', size: 983303188480, type: 'file', url: 'http://localhost/The+Legend+of+Korra+%282012%29+-+S04E03+-+The+Coronation+%281080p+BluRay+x265+RCVR%29.mkv'},
    {format: 'mkv', name: 'The Legend of Korra (2012) - S04E04 - The Calling (1080p BluRay x265 RCVR).mkv', parent: 'D: \\Vidéos\\Avatar - The Legend of Korra', path: 'D: \\Vidéos\\Avatar - The Legend of Korra\\The Legend of Korra (2012) - S04E04 - The Calling (1080p BluRay x265 RCVR).mkv', size: 983303188480, type: 'file', url: 'http://localhost/The+Legend+of+Korra+%282012%29+-+S04E04+-+The+Calling+%281080p+BluRay+x265+RCVR%29.mkv'},
    {format: 'mkv', name: 'The Legend of Korra (2012) - S04E05 - Enemy at the Gates (1080p BluRay x265 RCVR).mkv', parent: 'D: \\Vidéos\\Avatar - The Legend of Korra', path: 'D: \\Vidéos\\Avatar - The Legend of Korra\\The Legend of Korra (2012) - S04E05 - Enemy at the Gates (1080p BluRay x265 RCVR).mkv', size: 983303188480, type: 'file', url: 'http://localhost/The+Legend+of+Korra+%282012%29+-+S04E05+-+Enemy+at+the+Gates+%281080p+BluRay+x265+RCVR%29.mkv'},
    {format: 'mkv', name: 'The Legend of Korra (2012) - S04E06 - The Battle of Zaofu (1080p BluRay x265 RCVR).mkv', parent: 'D: \\Vidéos\\Avatar - The Legend of Korra', path: 'D: \\Vidéos\\Avatar - The Legend of Korra\\The Legend of Korra (2012) - S04E06 - The Battle of Zaofu (1080p BluRay x265 RCVR).mkv', size: 983303188480, type: 'file', url: 'http://localhost/The+Legend+of+Korra+%282012%29+-+S04E06+-+The+Battle+of+Zaofu+%281080p+BluRay+x265+RCVR%29.mkv'},
    {format: 'mkv', name: 'The Legend of Korra (2012) - S04E07 - Reunion (1080p BluRay x265 RCVR).mkv', parent: 'D: \\Vidéos\\Avatar - The Legend of Korra', path: 'D: \\Vidéos\\Avatar - The Legend of Korra\\The Legend of Korra (2012) - S04E07 - Reunion (1080p BluRay x265 RCVR).mkv', size: 983303188480, type: 'file', url: 'http://localhost/The+Legend+of+Korra+%282012%29+-+S04E07+-+Reunion+%281080p+BluRay+x265+RCVR%29.mkv'},
    {format: 'mkv', name: 'The Legend of Korra (2012) - S04E08 - Remembrances (1080p BluRay x265 RCVR).mkv', parent: 'D: \\Vidéos\\Avatar - The Legend of Korra', path: 'D: \\Vidéos\\Avatar - The Legend of Korra\\The Legend of Korra (2012) - S04E08 - Remembrances (1080p BluRay x265 RCVR).mkv', size: 983303188480, type: 'file', url: 'http://localhost/The+Legend+of+Korra+%282012%29+-+S04E08+-+Remembrances+%281080p+BluRay+x265+RCVR%29.mkv'},
    {format: 'mkv', name: 'The Legend of Korra (2012) - S04E09 - Beyond the Wilds (1080p BluRay x265 RCVR).mkv', parent: 'D: \\Vidéos\\Avatar - The Legend of Korra', path: 'D: \\Vidéos\\Avatar - The Legend of Korra\\The Legend of Korra (2012) - S04E09 - Beyond the Wilds (1080p BluRay x265 RCVR).mkv', size: 983303188480, type: 'file', url: 'http://localhost/The+Legend+of+Korra+%282012%29+-+S04E09+-+Beyond+the+Wilds+%281080p+BluRay+x265+RCVR%29.mkv'},
    {format: 'mkv', name: 'The Legend of Korra (2012) - S04E10 - Operation Beifong (1080p BluRay x265 RCVR).mkv', parent: 'D: \\Vidéos\\Avatar - The Legend of Korra', path: 'D: \\Vidéos\\Avatar - The Legend of Korra\\The Legend of Korra (2012) - S04E10 - Operation Beifong (1080p BluRay x265 RCVR).mkv', size: 983303188480, type: 'file', url: 'http://localhost/The+Legend+of+Korra+%282012%29+-+S04E10+-+Operation+Beifong+%281080p+BluRay+x265+RCVR%29.mkv'},
    {format: 'mkv', name: 'The Legend of Korra (2012) - S04E11 - Kuvira\'s Gambit (1080p BluRay x265 RCVR).mkv', parent: 'D: \\Vidéos\\Avatar - The Legend of Korra', path: 'D: \\Vidéos\\Avatar - The Legend of Korra\\The Legend of Korra (2012) - S04E11 - Kuvira\'s Gambit (1080p BluRay x265 RCVR).mkv', size: 983303188480, type: 'file', url: 'http://localhost/The+Legend+of+Korra+%282012%29+-+S04E11+-+Kuvira%27s+Gambit+%281080p+BluRay+x265+RCVR%29.mkv'},
    {format: 'mkv', name: 'The Legend of Korra (2012) - S04E12 - Day of the Colossus (1080p BluRay x265 RCVR).mkv', parent: 'D: \\Vidéos\\Avatar - The Legend of Korra', path: 'D: \\Vidéos\\Avatar - The Legend of Korra\\The Legend of Korra (2012) - S04E12 - Day of the Colossus (1080p BluRay x265 RCVR).mkv', size: 983303188480, type: 'file', url: 'http://localhost/The+Legend+of+Korra+%282012%29+-+S04E12+-+Day+of+the+Colossus+%281080p+BluRay+x265+RCVR%29.mkv'},
    {format: 'mkv', name: 'The Legend of Korra (2012) - S04E13 - The Last Stand (1080p BluRay x265 RCVR).mkv', parent: 'D: \\Vidéos\\Avatar - The Legend of Korra', path: 'D: \\Vidéos\\Avatar - The Legend of Korra\\The Legend of Korra (2012) - S04E13 - The Last Stand (1080p BluRay x265 RCVR).mkv', size: 983303188480, type: 'file', url: 'http://localhost/The+Legend+of+Korra+%282012%29+-+S04E13+-+The+Last+Stand+%281080p+BluRay+x265+RCVR%29.mkv'},

  ];

  constructor() {}

  getFiles(folder: Folder | Library): Observable<LibraryFile[]> {
    return of(this.files).pipe(
      map(files => files.filter(file => file.parent === folder.path)),
      map(files => files.sort((a, b) => a.path.localeCompare(b.path))),
      /*map(files => files.sort((a, b) => {
        if (a.type === 'directory' && b.type !== 'directory') {
          return -1;
        }
        if (a.type !== 'directory' && b.type === 'directory') {
          return 1;
        }
        return 0;
      }))*/
    );
  }

  getLibraries(): Observable<Library[]> {
    return of([
      this.movies,
      this.shows,
      this.korra
    ]);
  }

}
